[build]
  publish = "build"

  command = "npm run build"

  functions = "functions"

[[redirects]]
  from = "/*"

  to = "/index.html"

  status = 200

[[headers]]
  for = "/*"

  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "OPTIONS, GET"
    Access-Control-Max-Age = 2592000